### ISSUE TITLE
Please consider submitting to TeachML workshop

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/machine-learning-librarians-archivists#47]
Hi,

we (@oliverguhr, @kmkinnaird and myself) are organizing a workshop at ECMLPKDD 2021 and we are looking for papers!
https://teaching-ml.github.io/2021/#paper-submission
The submission are not expected to be super long, around 4 pages, and the deadline is June 23. But with this, we hope to provide people the opportunity to make their work count with respect to number of papers. ;-) Moreover, it is a chance that you get feedback on your motivations and implementations from the community at large.

Based on a blog post by @tobyhodges, I became aware of your project. So I thought you are potentially interested in this opportunity. Feel free to close this issue at will.

Best,
Peter

**Comment by MikeTrizna** [comment]
Thanks for bringing this up, @psteinb. We submitted a paper yesterday through the system, so hopefully we can join you all in September!
