### ISSUE TITLE
check that the setup instructions are up to date (e.g., update version numbers)

### ISSUE THREAD

**Issue by noramcgregor** [carpentries-incubator/machine-learning-librarians-archivists#60]
Currently, https://carpentries-incubator.github.io/machine-learning-librarians-archivists/setup.html is empty because the lesson doesn't require any setup. It would be good to mention that on this page.

**Comment by PhilReedData** [comment]
We are using this issue as a real demonstration in the lesson sprint today. I will put in a suggested sentence in a pull request to replace the TODO marker.
