### ISSUE TITLE
Renumber episodes

### ISSUE THREAD

**Issue by chennesy** [carpentries-incubator/machine-learning-librarians-archivists#79]
Hi AI for GLAM team,

While the content in the second and third episodes seems to be different after they were split up, they both still have the same title and overview questions/objectives. So the [current lesson schedule](https://carpentries-incubator.github.io/machine-learning-librarians-archivists/) makes it appear as if two episodes are called "Artificial Intelligence (AI) and Machine Learning (ML) in a nutshell." 

Related: in the[ _episodes directory](https://github.com/carpentries-incubator/machine-learning-librarians-archivists/tree/gh-pages/_episodes) it looks like the episodes should be renumbered to clarify the proper order.

p.s. This lesson is now listed on the LC lessons page under Extended Curriculum!

**Comment by davanstrien** [comment]
Thanks @chennesy, we'll hopefully get some time to do a bit of a tidy of this lesson soon :) cc @noramcgregor @MikeTrizna @mark-bell-tna 

>p.s. This lesson is now listed on the LC lessons page under Extended Curriculum!

That's awesome to hear! Hopefully knowing that can give us a bit of a kick to tidy up some of this material!

**Comment by chennesy** [comment]
Looks like this was addressed so closing the issue out. Thanks!
