### ISSUE TITLE
Links in references are not clickable

### ISSUE THREAD

**Issue by b2m** [carpentries-incubator/machine-learning-librarians-archivists#88]
The links in the source material references are not clickable.

This seems to be a markdown issue and should be easily fixable.

This applies to Lesson 5, 6 and 7.

To make the links clickable we might just have to put the links into angle brackets.

References #63

**Comment by b2m** [comment]
I just noticed that the same applies for the reference page.

Will update my pull request accordingly.

**Comment by Naumann-Kai** [comment]
There is one link on scikit learn flowchart that does not exist yet.

https://carpentries-incubator.github.io/machine-learning-librarians-archivists/04-what-is-ml-good-at/index.html#classical-machine-learning-and-deep-learning
